# Site settings
title: 求仁得仁
header-img: "img/2.jpg"
tagline: "cn"  
description: "reason_W成龙| For Reason,For Real"  
baseurl: ""
url: "http://reasonW.github.io"  
encoding: UTF-8
# About/contact
owner: 
  name: "reasonW "
  email: charlewander@gmail.com
  bio: "有朋自远方来，不亦说乎"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
twitter_username: 
github_username: reasonW
facebook_username: 
weibo_username: reason_W成龙
zhihu_username: reason_W

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
gems: [jekyll-paginate]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "reason_W成龙"
      header-img: "img/6.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
